//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class guests_currently_living_in_the_hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guests_currently_living_in_the_hotel()
        {
            this.invoice_for_payment = new HashSet<invoice_for_payment>();
        }
    
        public string floor { get; set; }
        public string nomer { get; set; }
        public string kategoria { get; set; }
        public string client_ID { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
    
        public virtual grafik_yborki_nomerov grafik_yborki_nomerov { get; set; }
        public virtual otchet_po_oplate otchet_po_oplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_for_payment> invoice_for_payment { get; set; }
    }
}
