//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_for_payment
    {
        public int id { get; set; }
        public string artikul { get; set; }
        public string tovar { get; set; }
        public string kolichestvo { get; set; }
        public decimal cena { get; set; }
        public decimal stavkaNDS { get; set; }
        public decimal summaNDS { get; set; }
        public decimal summa { get; set; }
    
        public virtual guests_currently_living_in_the_hotel guests_currently_living_in_the_hotel { get; set; }
    }
}
