//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_4.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class name_database2Entities : DbContext
    {
        private static name_database2Entities _context;
        public name_database2Entities()
            : base("name=name_database2Entities")
        {
        }
        public static name_database2Entities GetContext()
        {
            if (_context == null)
                _context = new name_database2Entities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grafik_yborki_nomerov> grafik_yborki_nomerov { get; set; }
        public virtual DbSet<guests_currently_living_in_the_hotel> guests_currently_living_in_the_hotel { get; set; }
        public virtual DbSet<invoice_for_payment> invoice_for_payment { get; set; }
        public virtual DbSet<Nomernoi_fond> Nomernoi_fond { get; set; }
        public virtual DbSet<otchet_po_oplate> otchet_po_oplate { get; set; }
        public virtual DbSet<report_on_the_state_of_the_room_stock_as_of_date> report_on_the_state_of_the_room_stock_as_of_date { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
