//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomernoi_fond
    {
        public int ID { get; set; }
        public string floor { get; set; }
        public int nomer { get; set; }
        public string kategoria { get; set; }
    }
}
