//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class otchet_po_oplate
    {
        public string client_ID { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string kategoria_nomera { get; set; }
        public System.DateTime data_vezda { get; set; }
        public System.DateTime data_viezda { get; set; }
        public decimal summa { get; set; }
        public decimal oplacheno { get; set; }
    
        public virtual guests_currently_living_in_the_hotel guests_currently_living_in_the_hotel { get; set; }
    }
}
