//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_on_the_state_of_the_room_stock_as_of_date
    {
        public string floor_ID { get; set; }
        public string nomer { get; set; }
        public string kategoria { get; set; }
        public string status { get; set; }
        public System.DateTime data_viezda { get; set; }
    
        public virtual grafik_yborki_nomerov grafik_yborki_nomerov { get; set; }
    }
}
